/** @type {import('tailwindcss').Config} */
module.exports = {
  content: ["./src/**/*.{js,jsx,ts,tsx}", "./App.tsx"],
  presets: [require("nativewind/preset")],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        canvas: "#F6F6FB",
        surface: "#FFFFFF",
        "surface-elevated": "#FFFFFF",
        "field-bg": "#EFF0F7",
        ink: "#14151C",
        "ink-secondary": "#5F6478",
        "ink-muted": "#9AA0B4",
        accent: "#6657F2",
        "accent-deep": "#7C6BFF",
        "accent-soft": "rgba(102,87,242,0.12)",
        danger: "#FF6B5B",
        "danger-soft": "rgba(255,107,91,0.12)",
        success: "#2FAE77",
        "success-soft": "rgba(47,174,119,0.14)",
        warning: "#E8960C",
        "warning-soft": "rgba(232,150,12,0.14)",
        line: "#E5E6F0",
        "line-strong": "#D4D6E6",
        "on-accent": "#FFFFFF",
        "track-bg": "#EDEEF5",
        "chip-bg": "#F0F1F7",
        "button-secondary-bg": "#ECEDF5",
        // dark palette
        "canvas-dark": "#0B0B10",
        "surface-dark": "#101016",
        "surface-elevated-dark": "#15151E",
        "field-bg-dark": "#0E0E14",
        "ink-dark": "#F2F2F8",
        "ink-secondary-dark": "#8B90A6",
        "ink-muted-dark": "#565B70",
        "accent-dark": "#7C6BFF",
        "accent-deep-dark": "#8B7CFF",
        "accent-soft-dark": "rgba(124,107,255,0.16)",
        "danger-dark": "#FF7A6B",
        "danger-soft-dark": "rgba(255,122,107,0.12)",
        "success-dark": "#3ECB8E",
        "success-soft-dark": "rgba(62,203,142,0.14)",
        "warning-dark": "#F5B342",
        "warning-soft-dark": "rgba(245,179,66,0.14)",
        "line-dark": "#1B1B25",
        "line-strong-dark": "#272733",
        "on-accent-dark": "#FFFFFF",
        "track-bg-dark": "#0E0E14",
        "chip-bg-dark": "#17171F",
        "button-secondary-bg-dark": "#1A1A24",
      },
      fontFamily: {
        display: ["SpaceGrotesk_500Medium"],
        "display-bold": ["SpaceGrotesk_700Bold"],
        body: ["Inter_400Regular"],
        "body-medium": ["Inter_500Medium"],
        "body-semibold": ["Inter_600SemiBold"],
        mono: ["JetBrainsMono_400Regular"],
        "mono-medium": ["JetBrainsMono_500Medium"],
      },
      fontSize: {
        "2xs": ["11px", { lineHeight: "14px" }],
      },
    },
  },
  plugins: [],
};
